# Use REST Client plugin for VS Code to test the following requests
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// Create player
POST http://localhost:8080/api/players
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "name" : "Meggie",
  "age" : 32,
  "health" : 145
}

###
// Player by ID
GET http://localhost:8080/api/players/1
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

###
// Players list
GET http://localhost:8080/api/players
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

###
// Kill a player
PATCH http://localhost:8080/api/players/1/kill
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

###
// Create object
POST http://localhost:8080/api/objects
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "name" : "dragon",
  "value" : 999
}

###
// Objects list
GET http://localhost:8080/api/objects
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

###
// Get object by ID
GET http://localhost:8080/api/objects/1
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

###
// Upgrade object
PATCH http://localhost:8080/api/objects/1/upgrade
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "value": -100
}

###
// Destroy item
DELETE http://localhost:8080/api/objects/1
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

###
// Player picks object
PATCH http://localhost:8080/api/players/1/pick
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "object": 5
}

###
// Arm player with object
PATCH http://localhost:8080/api/players/1/equip
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "object": 1
}

###
// Player attacks
PATCH http://localhost:8080/api/players/1/attack
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "target": 2
}

###
// Player steal bag
PATCH http://localhost:8080/api/players/1/steal
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER

{
  "target": 2
}

###
// Player resurrect
PATCH http://localhost:8080/api/players/1/resurrect
Content-Type: application/json
Authorization: Bearer TOKEN_PLACEHOLDER